apiVersion: v1
kind: Service
metadata:
  name: testdb-federated
  namespace: redis
  annotations:
    federation.tigera.io/serviceSelector: federation == "yes"
spec:
  ports:
    - name: redis
      port: 11069
      protocol: TCP
  type: ClusterIP